### ISSUE TITLE
Crash when swiping back from character page

### ISSUE THREAD

**Issue by HotarunIchijou** [axiel7/AniHyou-android#9]
**Describe the bug**
When I go to character/staff page and swipe back,the app crashes

**To Reproduce**
1. Go to any anime or manga title
2. Click on any character or staff
3. Swipe back
4. App crashes

**Expected behavior**
It shouldn't crash

**Screenshots**
Cant attach screen record, so here's mega link
https://mega.nz/file/R7ZkAIbb#S0fmCjqlMQYEXX70A6QFMf56YOAQ9I1VgEai9GNnjdw

**Enviroment (required)**
 - Device model: pixel 5a
 - Android version: android 14
 - App version: 1.1.7

**Additional context**
Also I noticed that there's actually no predecitve back gesture, as it written in changelog, so I guess it can be related to this

**Comment by axiel7** [comment]
I also thought it was related to the predecitve back gesture but it seems to be an issue with WebView and the tabs in the character/staff screen, because it works fine in the profile bio. I'll see what can I do.

Also right now the predecitve back gesture is only supported when exiting the app, I need to wait for Google to be able to implement within the screens of the app.

**Comment by axiel7** [comment]
I applied a temprary fix, [download](https://github.com/axiel7/AniHyou-android/releases/tag/1.1.7) the release again

**Comment by HotarunIchijou** [comment]
Doesn't crashes now, but predictive back gesture is still doesn't work
